# Generated by Django 5.0.7 on 2024-08-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('cabaña_hospedado', models.CharField(max_length=25)),
                ('dia_en_el_que_se_hospedo', models.DateField()),
                ('comentario', models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('fecha_ingreso', models.DateField()),
                ('noches_de_estadia', models.IntegerField()),
                ('cabaña', models.CharField(max_length=40)),
                ('total_a_pagar', models.IntegerField()),
                ('codigo_de_reserva' ,  models.IntegerField())
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=40)),
            ],
        ),
    ]
